version: '2'

services:
  website:
    build: .
    working_dir: '/var/www/html'
    command: 'bash -c "php composer.phar install; apache2-foreground"'
    ports:
      - '8080:80'
    volumes:
      - ./site:/var/www/html
