version: '2'

services:
  website:
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=www.dpstudios.es,dpstudios.es
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=www.dpstudios.es,dpstudios.es
      - LETSENCRYPT_EMAIL=daniel@dpstudios.es
    expose:
      - "80"
    networks:
      - nginx-proxy
    volumes:
      - ./site:/var/www/html

networks:
  nginx-proxy:
    external: true
