version: '2'

services:
  website:
    build: .
    restart: always
    environment:
      - LETSENCRYPT_HOST=dpstudios.es,www.dpstudios.es
      - LETSENCRYPT_EMAIL=daniel@dpstudios.es
      - VIRTUAL_HOST=dpstudios.es,www.dpstudios.es
      - VIRTUAL_PROTO=http
    networks:
      - nginx-proxy
    volumes:
      - ./site:/var/www/html

networks:
  nginx-proxy:
    external: true
